### ISSUE TITLE
Is the code you uploaded not complete yet?

### ISSUE THREAD

**Issue by Explorermomo** [luoyuanlab/SHINE#1]
Why can't I find SHyGNN

![1681997814064](https://user-images.githubusercontent.com/65749342/233383432-7c6f76d6-da3e-4be9-a399-9c9be05691d8.png)

**Comment by foresthao** [comment]
me too

**Comment by luoyuanlab** [comment]
Thanks for reporting the issue. SHyGNN was the name used during ablation experiments and isn't needed in the .py file. I've updated the code. Hope this helps!
