### ISSUE TITLE
A strange phenomenon in the training process

### ISSUE THREAD

**Issue by Explorermomo** [luoyuanlab/SHINE#3]
Hello, I would like to ask a question, that is, will the phenomenon of "Train Loss: nan f1: 0.000; Val Loss: nan f1 = 0.000" suddenly appear during the network training process, which causes the test f1 to only reach a maximum of 0.55 Magnitude.

**Comment by luoyuanlab** [comment]
Hmmm, I don't recall seeing this, did you check the gradient? Might be gradient explosion.

**Comment by Explorermomo** [comment]
This phenomenon occurs when I add the regular term.

In addition, please allow me to ask another question. During the training process on the DisGeNet task, the "train loss" will be far greater than the "val loss". "Val loss" will first decrease and then increase, but f1 is still increasing. situation? Does the GisGeNet dataset have other division ratios, such as 7:2:1 or 8:1:1.

Sorry to bother you, thank you very much.

**Comment by luoyuanlab** [comment]
What do you mean by "add the regular term"? The regularization term? Would you mind pointing to which file which line?

DisGeNet has the same division ratio in the experiment.

**Comment by Explorermomo** [comment]
Yes, the above situation will appear after adding Hypergraph regularization. Have you tried other division ratios of DisGeNet? The best model results are trained with a dataset ratio of 6:2:2?

**Comment by luoyuanlab** [comment]
I haven't tried other division ratios, just 6:2:2, and the split was fixed from the beginning, so that the model and I won't accidentally look into test data. 

You can try reducing nratio (say 0.1) to see if it helps.
