### ISSUE TITLE
Gradient explosion

### ISSUE THREAD

**Issue by jacksliu** [luoyuanlab/SHINE#4]
Hi, Thanks for providing source code. When I run this file "train_val_test_SHINEreg.py" with TCGA dataset, the train Loss will occur nan. I checked the first epoch occurring train Loss nan. The gradient of model's parameters quite large. I try to set the nratio to 0.1, it will also occur train Loss nan around epoch 1450 and the test f1 is 0.4653. How can I solve this problem? Would like to share your configuration of TCGA dataset? Thanks.

**Comment by luoyuanlab** [comment]
I've updated the code including the example config, please try it. Hope that helps.

**Comment by jacksliu** [comment]
Thanks!
