### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by cutecharmingkid** [luoyuanlab/SHINE#6]
This error occurs when running the code, how to solve it?
![1691460081775](https://github.com/luoyuanlab/SHINE/assets/102043624/76408cc3-d047-4792-857c-e0eae63c3282)
![image](https://github.com/luoyuanlab/SHINE/assets/102043624/7c125fbb-6462-498a-a564-560b316b5b98)

**Comment by luoyuanlab** [comment]
You need to set up the directory structure as indicated.

**Comment by cutecharmingkid** [comment]
> You need to set up the directory structure as indicated.

sorry , i can't understand how to set up the directory structure.Can you tell me more specificly?

**Comment by luoyuanlab** [comment]
You need to have data folder under root dir, then datasets folder under data, etc. etc.
